# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 黄琦雲的博客
description: > # this means to ignore newlines until "baseurl:"
  基于 jekyll 的 Github Pages 个人博客网站，技术的学习、总结、分享与提升
baseurl: ""
url: "https://knightyun.github.io"
permalink: /:year/:month/:day/:title
repository: knightyun/knightyun.github.io
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/knightyun"
user: "黄琦雲"
user_email: "2386209384@qq.com"
# contact_url: "https://goo.gl/tVljbV"
# google_tracking_id: "UA-96359860-1"
# google_site_verification: "UA-96359860-1"
# disqus_shortname: "黄琦雲"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
sass:
  style: compressed
future: true